version: '3.8'
services:
  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
  python_app:
    build: ./notebook
    image: "${PYTHON_APP_IMAGE:-default-python-app-image}"
    volumes:
      - ./notebook:/usr/src/app
    depends_on:
      - neo4j
