version: '3'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: on-failure
    # volumes:
      # - .data:/data
      # - '$HOME/neo4j/data:/data'
      # - '$HOME/neo4j/conf/:/conf/'
    environment:
      - NEO4J_AUTH=neo4j/test
    command: neo4j
#   python_app:
#     build: ..
#     # volumes:
#     #   - .:/workspace
#     environment:
#       - NEO4J_URI=bolt://neo4j:7687
#       - NEO4J_USERNAME=neo4j
#       - NEO4J_PASSWORD=test
#     depends_on:
#       - neo4j

# # volumes:
#   # neo4j-data:
